# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 0.1.2
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fds_api_gen_client.api.covariance_matrix_api import CovarianceMatrixApi


class TestCovarianceMatrixApi(unittest.TestCase):
    """CovarianceMatrixApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CovarianceMatrixApi()

    def tearDown(self) -> None:
        pass

    def test_create_covariance_matrix(self) -> None:
        """Test case for create_covariance_matrix

        """
        pass

    def test_create_diagonal_covariance_matrix(self) -> None:
        """Test case for create_diagonal_covariance_matrix

        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        """
        pass

    def test_retrieve1(self) -> None:
        """Test case for retrieve1

        """
        pass

    def test_retrieve_all9(self) -> None:
        """Test case for retrieve_all9

        """
        pass


if __name__ == '__main__':
    unittest.main()
