# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 0.1.2
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fds_api_gen_client.api.ground_station_api import GroundStationApi


class TestGroundStationApi(unittest.TestCase):
    """GroundStationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroundStationApi()

    def tearDown(self) -> None:
        pass

    def test_create_ground_station(self) -> None:
        """Test case for create_ground_station

        """
        pass

    def test_delete_ground_station(self) -> None:
        """Test case for delete_ground_station

        """
        pass

    def test_retrieve_all_stations(self) -> None:
        """Test case for retrieve_all_stations

        """
        pass

    def test_retrieve_ground_station(self) -> None:
        """Test case for retrieve_ground_station

        """
        pass


if __name__ == '__main__':
    unittest.main()
