# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 0.1.2
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fds_api_gen_client.api.token_api import TokenApi


class TestTokenApi(unittest.TestCase):
    """TokenApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TokenApi()

    def tearDown(self) -> None:
        pass

    def test_get_token(self) -> None:
        """Test case for get_token

        """
        pass


if __name__ == '__main__':
    unittest.main()
