# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 0.1.2
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fds_api_gen_client.api.maneuver_generation_api import ManeuverGenerationApi


class TestManeuverGenerationApi(unittest.TestCase):
    """ManeuverGenerationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ManeuverGenerationApi()

    def tearDown(self) -> None:
        pass

    def test_get_maneuver_generation(self) -> None:
        """Test case for get_maneuver_generation

        """
        pass

    def test_get_maneuver_generation_result(self) -> None:
        """Test case for get_maneuver_generation_result

        """
        pass

    def test_get_maneuver_generation_result_by_extrapolation_id(self) -> None:
        """Test case for get_maneuver_generation_result_by_extrapolation_id

        """
        pass

    def test_maneuver_generation_from_ids(self) -> None:
        """Test case for maneuver_generation_from_ids

        """
        pass

    def test_retrieve_all_maneuver_generations(self) -> None:
        """Test case for retrieve_all_maneuver_generations

        """
        pass


if __name__ == '__main__':
    unittest.main()
