# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 0.1.2
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fds_api_gen_client.models.maneuver_generation_command_dto import ManeuverGenerationCommandDto

class TestManeuverGenerationCommandDto(unittest.TestCase):
    """ManeuverGenerationCommandDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManeuverGenerationCommandDto:
        """Test ManeuverGenerationCommandDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManeuverGenerationCommandDto`
        """
        model = ManeuverGenerationCommandDto()
        if include_optional:
            return ManeuverGenerationCommandDto(
                delta_eccentricity = 1.337,
                delta_inclination = 1.337,
                delta_semi_major_axis = 1.337,
                id = '',
                initial_orbit_id = '',
                maximum_duration = 1.337,
                orbital_states_required = 'NONE',
                propagation_context_id = '',
                quaternion_step = 1.337,
                spacecraft_id = '',
                strategy_id = ''
            )
        else:
            return ManeuverGenerationCommandDto(
                delta_eccentricity = 1.337,
                delta_inclination = 1.337,
                delta_semi_major_axis = 1.337,
                initial_orbit_id = '',
                maximum_duration = 1.337,
                orbital_states_required = 'NONE',
                propagation_context_id = '',
                quaternion_step = 1.337,
                spacecraft_id = '',
                strategy_id = '',
        )
        """

    def testManeuverGenerationCommandDto(self):
        """Test ManeuverGenerationCommandDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
