# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 0.1.2
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fds_api_gen_client.api.orbit_api import OrbitApi


class TestOrbitApi(unittest.TestCase):
    """OrbitApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrbitApi()

    def tearDown(self) -> None:
        pass

    def test_create_keplerian_orbit(self) -> None:
        """Test case for create_keplerian_orbit

        """
        pass

    def test_delete_orbit(self) -> None:
        """Test case for delete_orbit

        """
        pass

    def test_retrieve_all2(self) -> None:
        """Test case for retrieve_all2

        """
        pass

    def test_retrieve_orbit_by_id(self) -> None:
        """Test case for retrieve_orbit_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
