# coding: utf-8

"""
    FDS API

    API for Flight Dynamics System

    The version of the OpenAPI document: 0.1.2
    Contact: contact@exotrail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fds_api_gen_client.models.orbit_determination_report_dto import OrbitDeterminationReportDto

class TestOrbitDeterminationReportDto(unittest.TestCase):
    """OrbitDeterminationReportDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrbitDeterminationReportDto:
        """Test OrbitDeterminationReportDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrbitDeterminationReportDto`
        """
        model = OrbitDeterminationReportDto()
        if include_optional:
            return OrbitDeterminationReportDto(
                estimated_states = [
                    fds_api_gen_client.models.orbital_state_dto.OrbitalStateDto(
                        covariance_matrix_id = '', 
                        creation_date = '', 
                        fitted_tle = fds_api_gen_client.models.tle.TLE(
                            line1 = '', 
                            line2 = '', ), 
                        id = '', 
                        mean_orbit_id = '', 
                        osculating_orbit_id = '', 
                        propagation_context_id = '', 
                        source = 'ORBIT_DETERMINATION', 
                        spacecraft_id = '', )
                    ],
                number_of_rejected_measurements = 56,
                number_of_used_measurements = 56,
                residuals_statistics = [
                    fds_api_gen_client.models.orbit_determination_residual_statistics_dto.OrbitDeterminationResidualStatisticsDto(
                        field = 'GPS_NMEA', 
                        id = '', 
                        mean = 1.337, 
                        median = 1.337, 
                        residuals = [
                            fds_api_gen_client.models.residual_dto.ResidualDto(
                                date = '', 
                                id = '', 
                                value = 1.337, )
                            ], 
                        standard_deviation = 1.337, )
                    ]
            )
        else:
            return OrbitDeterminationReportDto(
        )
        """

    def testOrbitDeterminationReportDto(self):
        """Test OrbitDeterminationReportDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
